config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'posts#index'
  resources :posts
  resources :comments,            only: [:new, :create, :destroy]
  resources :users,               only: [:index, :show]
  resources :friendship_requests, only: [:create]
  resources :friendships,         only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates :content, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/friendship_request.rb
class FriendshipRequest < ApplicationRecord
  belongs_to :from, class_name: 'User'
  belongs_to :to, class_name: 'User'

  # Deletes the provided request and creates a friendship between the users
  def self.accept(request)
    Friendship.create!(user: request.from, friend: request.to)
    request.destroy
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :users_who_commented, through: :comments, source: :author
  has_many :likes
  has_many :users_who_liked, through: :likes, source: :user

  validates :title, presence: true
  validates :content, presence: true

  scope :new_first, -> { order(created_at: :desc) }

  # Returns the Like ID belonging to a given user
  def like_id(user)
    likes.find_by(user: user).id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: %i[facebook]
  validates :name, presence: true, length: { maximum: 50 }

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :commented_posts, through: :comments, source: :post
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :initiated_friendships, class_name: 'Friendship',
                                   foreign_key: 'user_id'
  has_many :received_friendships,  class_name: 'Friendship',
                                   foreign_key: 'friend_id'
  has_many :friends_initiated, through: :initiated_friendships, source: :friend
  has_many :friends_received,  through: :received_friendships,  source: :user
  has_many :requests_sent,     class_name: 'FriendshipRequest',
                               foreign_key: 'from_id'
  has_many :requests_received, class_name: 'FriendshipRequest',
                               foreign_key: 'to_id'

  # Return all friends joining the two types using |(Set Union)
  def friends
    friends_initiated | friends_received
  end

  # Return the ids of all user's friends
  def friend_ids
    friends.map(&:id)
  end

  # Returns true if the user is friends with provided user.
  def friends_with?(user)
    friends.include?(user)
  end

  def allowed_feeds
    friend_ids << self.id
  end

  # Returns true if there is a friend request waiting for aproval of the given user
  def pending_request?(user)
    requests_sent.where(to: user).any?
  end

  # Returns true if User likes given post
  def likes?(post)
    liked_posts.where(id: post).any?
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    
  end

  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash[:success] = 'Comment Created!'
      redirect_back(fallback_location: posts_path) 
    end
  end

private
    
  def comment_params
    params.require(:comment).permit(:author_id, :post_id, :content)
  end
end

app/controllers/friendship_requests_controller.rb
class FriendshipRequestsController < ApplicationController
  def create
    request = FriendshipRequest.new(request_params)
    if request.save
      flash[:success] = 'Friend Request Sent!'
    else
      flash[:warning] = "We Were unable to send your request"
    end
    redirect_to users_path
  end

  private

    def request_params
      params.require(:request).permit(:from_id, :to_id)
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friendship = Friendship.new(friendship_params)
    if friendship.save
      FriendshipRequest.where(from: friendship.user, to: friendship.friend).delete_all
      flash[:success] = "You are now friends with #{friendship.user.name}!"
      redirect_to current_user
    end
  end

private

  def friendship_params
    params.require(:friendship).permit(:user_id, :friend_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    if current_user.likes.create!(post_id: params[:post_id])
      flash[:success] = 'Post liked'
      redirect_to posts_path
    end
  end

  def destroy
    like = Like.find(params[:id])
    if like.destroy
      flash[:success] = 'You no longer like this post'
      redirect_to posts_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where(author_id: current_user.allowed_feeds).new_first
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    post = Post.new(post_params)
    if post.save
      flash[:notice] = 'Post created!'
      redirect_to posts_path
    end
  end

  def edit
    
  end

  def update
    
  end

  def destroy
    
  end

private

  def post_params
    params.require(:post).permit(:author_id, :title, :content)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendship_requests_helper.rb
module FriendshipRequestsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Generates the gravatar img tag for provided user
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/comments/_form.html.erb
  <%= form_for Comment.new do |f| %>
    <%= f.hidden_field :author_id, value: author_id %>
    <%= f.hidden_field :post_id, value: post_id %>
    <%= f.label :content, 'Write a comment' %>
    <%= f.text_area :content %>

    <%= f.submit %>
  <% end %>

app/views/posts/_post.html.erb
<h3><%= post.title %></h3>

<% unless post.author.id == params[:id].to_i %>
  <p><em>by: <%= gravatar_for(post.author, size: 20) %> <%=  post.author.name %></em></p>
<% end %>
<p><%= post.content %></p>
<p>Likes: <%= post.likes.count %></p>
<% if current_user.likes?(post) %>
  <%= button_to 'unlike', like_path(post.like_id(current_user)), method: 'delete' %>
<% else %>
  <%= button_to 'like', likes_path(post_id: post)%>
<% end %>
<ul>
  <% post.comments.each do |comment| %>
    <li>
      <%= link_to comment.author.name, user_path(comment.author) %> wrote: <br>
      <%= comment.content %> <br>
      on <em><%= comment.created_at.strftime('%c') %></em>
    </li>
  <% end %>
</ul>
<%= render partial: 'comments/form', locals: { author_id: current_user.id,
                                               post_id: post.id } %>

app/views/posts/index.html.erb
<h1>Your Feed</h1>
<%= render @posts %>

app/views/posts/new.html.erb
<h1>Create a new post</h1>

<%= form_for @post do |f| %>
  <%= f.hidden_field :author_id %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit %>
<% end %>

app/views/users/_my_profile.html.erb
<h2>People who want to be your friend</h2>
<ul>
  <% @user.requests_received.each do |request| %>
    <li><%= link_to request.from.name, user_path(request.from) %> --
      <%= button_to 'Accept request',
          friendships_path(friendship: { user_id: request.from, friend_id: request.to }) %></li>
  <% end %>  
</ul>

app/views/users/_user.html.erb
<% unless current_user == user %>  
  <li>
    <%= gravatar_for(user, size: 40) %>
    <%= link_to user.name, user %> - <%= user.email %> 
    <div>
      <% if current_user.friends_with?(user) %>
        Friend
      <% elsif current_user.pending_request?(user) %>
        Evaluating your request
      <% else %>
        <%= button_to 'Send friend request',
            friendship_requests_path(request: { from_id: current_user, to_id: user }) %>
      <% end %>
    </div>
  </li>
<% end %>

app/views/users/index.html.erb
<h1>People</h1>
<ul>
  <%= render @users %>
</ul>

app/views/users/show.html.erb
<%= gravatar_for(@user) %>
<% if current_user == @user %>
  <h1>My profile</h1>
  <%= render 'my_profile' %>
<% else %>
  <h1><%= @user.name %>'s profile</h1>
  <%#= render 'user_profile' %> 
<% end %>
<h2>Posts</h2>
<%= render @user.posts.new_first %>